
words = []
words.append(input("Insert Noun"))
words.append(input("Insert Noun"))
words.append(input("Insert Noun"))
words.append(input("Insert Adjective"))
words.append(input("Insert Adjective"))
words.append(input("Insert Noun"))
words.append(input("Insert Noun"))
words.append(input("Insert Noun"))
words.append(input("Insert Adjective"))
words.append(input("Insert Noun"))
words.append(input("Insert Verb"))
words.append(input("Insert Noun"))
words.append(input("Insert Adjective"))
words.append(input("Insert Country"))
words.append(input("Insert Noun"))
words.append(input("Insert Noun"))
words.append(input("Insert Verb"))
words.append(input("Insert Adjective"))
words.append(input("Insert Country"))
words.append(input("Insert Noun"))
words.append(input("Insert Noun"))
words.append(input("Insert Noun"))
words.append(input("Insert Noun"))
words.append(input("Insert Noun"))
words.append(input("Insert Adjective"))
words.append(input("Insert Noun"))
words.append(input("Insert Adjective"))
words.append(input("Insert Noun"))
words.append(input("Insert Adjective"))
words.append(input("Insert Noun"))

print("%s, %s, and the %s. " % (words[0], words[1], words[2]))
print("These were all %s events but nothing could have been more %s, to Europe, " % (words[3], words[4]))
print("then the %s which was caused by the events of %s" % (words[5], words[6]))
print("%s was the %s disease at the time. " % (words[7], words[8]))
print("It was a bubonic plague meaning that %s, balls of puss" % words[9])
print("would start to %s all over your %s and it was %s. " % (words[10], words[11], words[12]))
print("It affected %s first but it spread throughout Europe like %s. " % (words[13], words[14]))
print("After this %s had %s, something very %s happened." % (words[15], words[16], words[17]))
print("%s started to build a better %s because they were seen " % (words[18], words[19]))
print("as the weaker %s at the time due to this %s." % (words[20], words[21]))
print("%s after the %s had wanted their country to be reborn because " % (words[22], words[23]))
print("the %s did not always have answers," % words[24])
print("%s were %s, and the %s was %s, hence The %s. " % (words[25], words[26], words[27], words[28], words[29]))


# 10 words that are put in
# At least one line where there is only one
# One needs to have at least two
