
noun1 = input("Insert Noun")
noun2 = input("Insert Noun")
noun3 = input("Insert Noun")
adjective1 = input("Insert Adjective")
adjective2 = input("Insert Adjective")
noun4 = input("Insert Noun")
noun5 = input("Insert Noun")
verb1 = input("Insert Verb ending with ed")
noun6 = input("Insert Noun")
disease = input("Insert disease")
adjective3 = input("Insert Adjective")
noun7 = input("Insert Noun")
verb2 = input("Insert Verb")
noun8 = input("Insert Noun")
adjective4 = input("Insert Adjective")
noun9 = input("Insert Noun")
country = input("Insert country")
noun10 = input("Insert noun")
noun11 = input("Insert Noun")
country1 = input("Insert Country")
country2 = input("Insert Country")
disaster = input("Insert Natural disaster")
noun12 = input("Insert Noun")
verb3 = input("Insert Verb")
noun13 = input("Insert Noun")
adjective = input("Insert Adjective")
noun14 = input("Insert Noun")
noun15 = input("Noun")
noun16 = input("Insert Noun")
noun17 = input("Insert Noun")
adjective5 = input("Insert Adjective")
noun = input("Insert Noun")
noun18 = input("insert noun")
print("%s, %s, and the %s. These were all %s events but nothing could have been more %s, to Europe, " %
 (noun1, noun2, noun3, adjective1, adjective2))
print("then the %s which was caused by the events of %s" %(noun4,noun5))
print("%s was the %s disease at the time. " %(noun6,adjective3))
print("It was a bubonic plague meaning that %s, balls of puss" % noun7)
print("would start to %s all over your %s and it was %s. "% (verb1,noun8 ,adjective4))
print("It affected %s first but it spread throughout Europe like %s. " %(country1,noun9))
print("After this %s had %s, something very %s happened.")
print("%s started to build a better %s because they were seen ")
print("as the weaker %s at the time due to this %s.")
print("%s after the %s had wanted their country to be reborn because ")
print("the %s did not always have answers,")
print("%s were %s, and the %s was %s, hence The %s. ")

#10 words that are put in
#At least one line where there is only one
#One needs to have at least two